#!/bin/bash

# This is where we load the official YunoHost helpers
source /usr/share/yunohost/helpers

ynh_script_progression --message="Installing from repositories" --weight=1

apt-get install crowdsec crowdsec-firewall-bouncer-nftables
